//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsWorkspaceManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsWorkspaceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   登録を解除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmRemoveTemplate {
            get {
                return ResourceManager.GetString("Msg_ConfirmRemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一のテンプレートフォルダ名が登録されています。名前を変更して登録するか登録済みのテンプレートフォルダを削除して再度登録してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DuplicateTemplate {
            get {
                return ResourceManager.GetString("Msg_DuplicateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成先のフォルダがすでに存在しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_DestFolderExists {
            get {
                return ResourceManager.GetString("Msg_Err_DestFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルアクセスエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_FileAccess {
            get {
                return ResourceManager.GetString("Msg_Err_FileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効なフォルダが指定されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_InvalidFolder {
            get {
                return ResourceManager.GetString("Msg_Err_InvalidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスクの空き容量が足りません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_NoDiskSpace {
            get {
                return ResourceManager.GetString("Msg_Err_NoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込み権限がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_NoWritePermission {
            get {
                return ResourceManager.GetString("Msg_Err_NoWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーパスが長すぎるため作業フォルダの作成に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_PathTooLong {
            get {
                return ResourceManager.GetString("Msg_Err_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みのテンプレートファイルが移動または削除されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_TemplateMissing {
            get {
                return ResourceManager.GetString("Msg_Err_TemplateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークスペースの作成が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_WorkspaceCreated {
            get {
                return ResourceManager.GetString("Msg_WorkspaceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Complete {
            get {
                return ResourceManager.GetString("Title_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
    }
}
